// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCLdmELqdrvb-AE6nFocQsLjdrRSwIusw',
    appId: '1:714875757254:web:fd8b20601693058d72edc7',
    messagingSenderId: '714875757254',
    projectId: 'my-fire-4a4d1',
    authDomain: 'my-fire-4a4d1.firebaseapp.com',
    databaseURL: 'https://my-fire-4a4d1-default-rtdb.firebaseio.com',
    storageBucket: 'my-fire-4a4d1.firebasestorage.app',
    measurementId: 'G-02VHD2RYK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHtd3NBhRTjeJH089BdJ5E2Gucq4FGY9Q',
    appId: '1:714875757254:android:44d13d0cf27d9ae472edc7',
    messagingSenderId: '714875757254',
    projectId: 'my-fire-4a4d1',
    databaseURL: 'https://my-fire-4a4d1-default-rtdb.firebaseio.com',
    storageBucket: 'my-fire-4a4d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1iAB59uqfngXwpscoKduXjCPdIQ5lznk',
    appId: '1:714875757254:ios:2d7eb717bd15855c72edc7',
    messagingSenderId: '714875757254',
    projectId: 'my-fire-4a4d1',
    databaseURL: 'https://my-fire-4a4d1-default-rtdb.firebaseio.com',
    storageBucket: 'my-fire-4a4d1.firebasestorage.app',
    androidClientId: '714875757254-69c1tmkfjlok70d6vd63qkp0c1isq4ej.apps.googleusercontent.com',
    iosClientId: '714875757254-o10b7qpisl4g8o6dh0ravsp2cjkguoog.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1iAB59uqfngXwpscoKduXjCPdIQ5lznk',
    appId: '1:714875757254:ios:2d7eb717bd15855c72edc7',
    messagingSenderId: '714875757254',
    projectId: 'my-fire-4a4d1',
    databaseURL: 'https://my-fire-4a4d1-default-rtdb.firebaseio.com',
    storageBucket: 'my-fire-4a4d1.firebasestorage.app',
    androidClientId: '714875757254-69c1tmkfjlok70d6vd63qkp0c1isq4ej.apps.googleusercontent.com',
    iosClientId: '714875757254-o10b7qpisl4g8o6dh0ravsp2cjkguoog.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCLdmELqdrvb-AE6nFocQsLjdrRSwIusw',
    appId: '1:714875757254:web:1200e603ce89e4e872edc7',
    messagingSenderId: '714875757254',
    projectId: 'my-fire-4a4d1',
    authDomain: 'my-fire-4a4d1.firebaseapp.com',
    databaseURL: 'https://my-fire-4a4d1-default-rtdb.firebaseio.com',
    storageBucket: 'my-fire-4a4d1.firebasestorage.app',
    measurementId: 'G-NYMQMQ4V50',
  );
}
